version: '3.7'

services:
  postgres:
    image: postgres:10.6-alpine
    container_name: go_postgres
    ports:
      - "5492:5432"
    environment:
      - POSTGRES_USER=dbadmin 
      - POSTGRES_PASSWORD=dbadmin

  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    container_name: krakend_designer
    ports:
      - "8787:80"
  
  krakend:
    image: devopsfaith/krakend:latest
    container_name: krakend
    volumes:
      - ./api_gateway:/etc/krakend
    ports:
      - "5000:5000"

  jaeger:
    container_name: jaeger
    networks: 
      - broker-kafka
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      
  file_server:
    image: jaxgeller/lwan
    container_name: file_server
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - 8002:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks: 
      - broker-kafka
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks: 
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - ./_script:/wait
    command: ["/wait/wait-for-it.sh", "--timeout=0", "zookeeper:2181", "--", "/etc/confluent/docker/run"]

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    networks: 
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  broker:
    container_name: broker
    image: pactfoundation/pact-broker:latest
    ports:
      - 9292:9292
    networks: 
      - broker-kafka
    environment:
      - PACT_BROKER_DATABASE_URL=postgresql://dbadmin:dbadmin@postgres:5432/postgres
      - PACT_BROKER_BASIC_AUTH_USERNAME=admin
      - PACT_BROKER_BASIC_AUTH_PASSWORD=admin
      - PACT_BROKER_LOG_LEVEL=INFO
      - PACT_BROKER_PORT=9292
    restart: on-failure
    depends_on:
      - postgres

networks: 
  broker-kafka:
    driver: bridge  